---
repos:
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.37.0
    hooks:
      - id: yamllint

  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.98.1
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
