apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cluster-configs
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - name: https://kubernetes.default.svc
      namespace: ''
      server: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - 'https://github.com/joggie/job-interview-task-gitops.git' # cluster configs
  sourceNamespaces:
    - '*'