apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: app
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - name: in-cluster
      namespace: app
      server: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
  sourceRepos:
    - 'https://github.com/joggie/job-interview-task-gitops.git' # cluster-config
    - 'https://stefanprodan.github.io/podinfo' # podinfo
  sourceNamespaces:
    - '*'