apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  labels:
    cluster:
spec:
  destination:
    namespace: cert-manager
    name:
  project: infrastructure
  sources:
    - repoURL: https://charts.jetstack.io
      targetRevision: v1.17.1
      chart: cert-manager
      helm:
        releaseName: cert-manager
    - repoURL: https://github.com/joggie/job-interview-task-gitops.git
      ref: values
      targetRevision: HEAD
  syncPolicy:
#   automated: {}  
    syncOptions:
      - CreateNamespace=true