type: LoadBalancer

# Entry points for HTTP and HTTPS
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

# Disable dashboard
ingressRoute:
  dashboard:
    enabled: false

# Exposed ports via Service
ports:
  web:
    exposedPort: 80
  websecure:
    exposedPort: 443
    tls:
      enabled: true

# Use as default IngressClass
ingressClass:
  enabled: true
  isDefaultClass: true

# Deployment settings
deployment:
  replicas: 1