apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
spec:
  destination:
    namespace: app
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: podinfo
    helm:
      values: |-
        logLevel: debug
        redis:
          enable: true
    repoURL: https://stefanprodan.github.io/podinfo
    targetRevision: 6.2.1
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
