---
global:
  domain: argocd.demo.nerdhome.at
dex:   # saml
  enabled: false
configs:
  cm:
    create: true
    url: https://argocd.demo.nerdhome.at
  rbac:
    create: true
    policy.default: role:readonly
  params:
    server.insecure: true
