apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../../../components/applications/argocd

patches:
- patch: |-
    - op: add
      path: /spec/sources/0/helm/valueFiles
      value: 
        - $values/argocd/clusters/interview-gitops-sks/applications/argocd/helm-values.yaml
  target:
    group: argoproj.io
    kind: Application
    name: argocd
    version: v1alpha1