apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  labels:
    cluster:
spec:
  destination:
    namespace: argocd
    name:
  project: argocd
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      targetRevision: 7.8.24
      chart: argo-cd
      helm:
        releaseName: argo-cd
    - repoURL: https://github.com/joggie/job-interview-task-gitops.git
      ref: values
      targetRevision: HEAD
  syncPolicy:
#   automated: {}  
    syncOptions:
      - CreateNamespace=true